version: '3'

volumes:
  data:

services:
  db_postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPassword
    ports:
     - "5434:5432"
    volumes:
     - data:/var/lib/postgres/data 
     - type: tmpfs
       target: /dev/shm
    networks:
      - backend

  api:
    image: node:16.14
    ports:
     - "3333:3333"
    working_dir: "/home/node/app"
    volumes: 
      - ./backend:/home/node/app
    command: "npm run dev"
    networks:
      - backend
      - frontend
    depends_on:
      - db_postgres

  web:
    image: node:16.14
    ports:
     - "5173:5173"
    working_dir: "/home/node/app"
    volumes: 
      - ./frontend:/home/node/app
    command: "npm run dev"
    networks:
      - frontend
    depends_on:
      - api

networks:
  backend:
    driver: "bridge"
  frontend:
    driver: "bridge"