version: '3'

volumes:
  data:

services:
  db_data:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - "5434:5432"
    volumes:
     - data:/var/lib/postgres/data 
     - type: tmpfs
       target: /dev/shm
    networks:
      - backend

  api:
    image: node:16.14
    
    ports:
     - "3333:3333"
    working_dir: "/home/node/app"
    volumes: 
      - ./backend:/home/node/app
    command: "npm run dev"
    networks:
      - backend
    depends_on:
      - db_data


networks:
  backend:
    driver: "bridge"